# -*- coding: utf-8 -*-
"""ATG_Assessment_AishwaryaKale.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hITIRpsNisJF7Fjnq1YKpeKq4aAR6prE
"""

class TextJustify:

  def justify(self,line,length):
      # split the line into word list
      words = line.split()
      maxLength = length
      res=self.mainJustify(words, maxLength)
      res = '\n'.join(map(str, res))
      return res

  def insertSpaces(self,string,maxLength, isLast):
    spaces = maxLength - len(string)
    stringList = string.split(' ') 
    # if last word or single word list , rerturn result with adding required spaces until max length
    if len(stringList) == 1 or isLast:
        return string + (' ' * spaces)
    # add required spaces to the string
    else:
        while spaces:
            for i in range(len(stringList) - 1):
                if spaces:
                    stringList[i] += ' '
                    spaces -= 1
                else:
                    break
    return ' '.join(stringList)

  def mainJustify(self, words, maxLength):   
      
      res = [] 
      curr_line = ""
      for word in words:
          # insert first word to empty  string
          if not curr_line:
              curr_line += word
          # append the word on same line if length of line & length of given word are within range of max length
          elif len(curr_line + ' ' + word) <= maxLength:
              curr_line += ' ' + word
          # if word cannot fit in same line , call another function and passing False flag for non-last word 
          else:
              res.append(self.insertSpaces(curr_line,maxLength, False))
              curr_line = word
      
      # for the last word ,pass True flag and append the returned result 
      res.append(self.insertSpaces(curr_line,maxLength, True))
      return res


if __name__ == "__main__":
    line = "The quick brown fox jumps over a lazy dog."
    length = 16
    tj = TextJustify()
    output = tj.justify(line,length)
    print(output)

